/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.Student;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import service.StudentServices;

/**
 *
 * @author LOGAN
 */
public class StudentView extends javax.swing.JFrame {

    public StudentView() {
        initComponents();
        retriveAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        teacherBtn = new javax.swing.JButton();
        studentBtn = new javax.swing.JButton();
        courseBtn = new javax.swing.JButton();
        GradesBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        names = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        startingYear = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        allStudentsTable = new javax.swing.JTable();
        searchTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        teacherBtn.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        teacherBtn.setText("Teacher");
        teacherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherBtnActionPerformed(evt);
            }
        });

        studentBtn.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        studentBtn.setText("Student");
        studentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentBtnActionPerformed(evt);
            }
        });

        courseBtn.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        courseBtn.setText("Courses");
        courseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseBtnActionPerformed(evt);
            }
        });

        GradesBtn.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        GradesBtn.setText("Grades");
        GradesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradesBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("School Management system");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(teacherBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(studentBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(courseBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GradesBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel8)))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherBtn)
                    .addComponent(studentBtn)
                    .addComponent(courseBtn)
                    .addComponent(GradesBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, -1));

        names.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        names.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namesActionPerformed(evt);
            }
        });
        jPanel1.add(names, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 176, 29));

        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel2.setText("Add Student");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel3.setText("E-mail");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        email.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 176, 29));

        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel4.setText("Phone");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        phone.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 176, 29));

        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel5.setText("Faculty:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Information Technology", "Education", "Business Management" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 176, 30));

        gender.add(male);
        male.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        male.setText("Male");
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        gender.add(female);
        female.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        female.setText("Female");
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel6.setText("Gender");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel7.setText("Starting Year");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        startingYear.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        startingYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startingYearActionPerformed(evt);
            }
        });
        jPanel1.add(startingYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 176, 29));

        delete.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, -1, -1));

        save.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        allStudentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Names", "E-mail", "Phone", "Faculty", "Gender", "Year"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        allStudentsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allStudentsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(allStudentsTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 684, -1));

        searchTxt.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jPanel1.add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 154, 33));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/icons8-search-24.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 110, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/icons8-search-24.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 110, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/icons8-print-24.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, -1, -1));

        jLabel10.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel10.setText("Names:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 290, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void retriveAll() {
        try {
            Registry theReg = LocateRegistry.getRegistry("127.0.0.1", 81);
            StudentServices services = (StudentServices) theReg.lookup("student");
            List<Student> studentObj = services.allStudents();
            DefaultTableModel tbModel = (DefaultTableModel) allStudentsTable.getModel();
            tbModel.setRowCount(0);
            for (Student student : studentObj) {
                int id = student.getStudentId();
                String names = student.getNames();
                String email = student.getEmail();
                String faculty = student.getFaculty();
                String startingYear = student.getStartingYear();

                tbModel.addRow(new Object[]{
                    id, names, email, faculty, startingYear
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void teacherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherBtnActionPerformed
        TeacherView teacher = new TeacherView();
        teacher.show();

        dispose();
    }//GEN-LAST:event_teacherBtnActionPerformed

    private void studentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentBtnActionPerformed
        StudentView student = new StudentView();
        student.show();

        dispose();
    }//GEN-LAST:event_studentBtnActionPerformed

    private void courseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseBtnActionPerformed
        CourseView course = new CourseView();
        course.show();

        dispose();
    }//GEN-LAST:event_courseBtnActionPerformed

    private void GradesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradesBtnActionPerformed
        GradeView grade = new GradeView();
        grade.show();

        dispose();
    }//GEN-LAST:event_GradesBtnActionPerformed

    private void namesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namesActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void startingYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startingYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startingYearActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        if (allStudentsTable.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Select a row To delete");
        } else {
            int choice = JOptionPane.showConfirmDialog(this, "Are you sure to delete");
            if (choice == JOptionPane.YES_OPTION) {
                int selectedRow = allStudentsTable.getSelectedRow();
                DefaultTableModel tbModel = (DefaultTableModel) allStudentsTable.getModel();
                Student stud = new Student();
                stud.setStudentId(Integer.parseInt(tbModel.getValueAt(selectedRow, 0).toString()));
                try {
                    Registry theReg = LocateRegistry.getRegistry("127.0.0.1", 81);
                    StudentServices service = (StudentServices) theReg.lookup("student");
                    Student StudentObj = service.deleteStudent(stud);

                    if (StudentObj != null) {
                        JOptionPane.showMessageDialog(this, "Data saved");
                        names.setText("");
                        email.setText("");
                        phone.setText("");
                        jComboBox1.setSelectedIndex(0);
                        gender.clearSelection();
                        startingYear.setText("");
                        retriveAll();
                    } else {
                        JOptionPane.showMessageDialog(this, "Something wrong");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }

            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        if (names.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Names can not be Empty");
        } else if (!isValidEmail(email.getText())) {
            JOptionPane.showMessageDialog(this, "Email not Valid");
        } else if (!phone.getText().matches("^07\\d{8}$")) {
            JOptionPane.showMessageDialog(this, "Phone number not Valid");
        } else if (jComboBox1.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Select Faculty");
        } else if (gender.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Select Gender");
        } else if (!startingYear.getText().matches("^\\d{4}$")) {
            JOptionPane.showMessageDialog(this, "Year formata YYYY");
        } else {
            try {
                Student stud = new Student();

                if (allStudentsTable.getSelectedRow() != -1) {
                    int selectedRow = allStudentsTable.getSelectedRow();
                    DefaultTableModel tbModel = (DefaultTableModel) allStudentsTable.getModel();
                    stud.setStudentId(Integer.parseInt(tbModel.getValueAt(selectedRow, 0).toString()));
                }
                stud.setNames(names.getText());
                stud.setEmail(email.getText());
                stud.setPhone(phone.getText());
                stud.setFaculty(jComboBox1.getSelectedItem().toString());
                stud.setGender(gender.getSelection().toString());
                if (male.isSelected()) {
                    stud.setGender(male.getText());
                } else {
                    stud.setGender(female.getText());
                }
                stud.setStartingYear(startingYear.getText());

                Registry theReg = LocateRegistry.getRegistry("127.0.0.1", 81);
                StudentServices service = (StudentServices) theReg.lookup("student");
                Student StudentObj = service.creatStudent(stud);

                if (StudentObj != null) {
                    JOptionPane.showMessageDialog(this, "Data saved");
                    names.setText("");
                    email.setText("");
                    phone.setText("");
                    jComboBox1.setSelectedIndex(0);
                    gender.clearSelection();
                    startingYear.setText("");
                    retriveAll();
                } else {
                    JOptionPane.showMessageDialog(this, "Something wrong");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void allStudentsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allStudentsTableMouseClicked
        int selectedRow = allStudentsTable.getSelectedRow();
        DefaultTableModel tbModel = (DefaultTableModel) allStudentsTable.getModel();

        names.setText(tbModel.getValueAt(selectedRow, 1).toString());
        email.setText(tbModel.getValueAt(selectedRow, 2).toString());
        phone.setText(tbModel.getValueAt(selectedRow, 3).toString());
        jComboBox1.setSelectedItem(tbModel.getValueAt(selectedRow, 4).toString());
        if (tbModel.getValueAt(selectedRow, 4).toString().equals("Male")) {
            male.setSelected(true);
        } else {
            female.setSelected(true);
        }
        startingYear.setText(tbModel.getValueAt(selectedRow, 6).toString());
    }//GEN-LAST:event_allStudentsTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (searchTxt.getText().trim().isEmpty() || !searchTxt.getText().matches("^[0-9]*$")) {
            JOptionPane.showMessageDialog(this, "Search not valid\nOnly Search Ids");
        } else {
            Student stud = new Student();
            int theId = Integer.parseInt(searchTxt.getText());
            stud.setStudentId(theId);
            try {
                Registry theReg = LocateRegistry.getRegistry("127.0.0.1", 81);
                StudentServices service = (StudentServices) theReg.lookup("student");
                Student StudentObj = service.searchStudent(stud);

                if (StudentObj != null) {
                    DefaultTableModel tbModel = (DefaultTableModel) allStudentsTable.getModel();
                    tbModel.setRowCount(0);

                    Integer id = StudentObj.getStudentId();
                    String names = StudentObj.getNames();
                    String email = StudentObj.getEmail();
                    String phone = StudentObj.getPhone();
                    String faculty = StudentObj.getFaculty();
                    String gender = StudentObj.getGender();
                    String startingYear = StudentObj.getStartingYear();
                    tbModel.addRow(new Object[]{
                        id, names, email, phone, faculty, gender, startingYear});
                } else {
                    JOptionPane.showMessageDialog(this, "No Results");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            allStudentsTable.print();
        } catch (PrinterException ex) {
            Logger.getLogger(StudentView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    public static boolean isValidEmail(String email) {
        String regex = "^[\\w!#$%&'*+/=?^`{|}~-]+(?:\\.[\\w!#$%&'*+/=?^`{|}~-]+)*@(?:[\\w](?:[\\w-]*[\\w])?\\.)+[\\w](?:[\\w-]*[\\w])?$";
        return Pattern.matches(regex, email);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GradesBtn;
    private javax.swing.JTable allStudentsTable;
    private javax.swing.JButton courseBtn;
    private javax.swing.JButton delete;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField names;
    private javax.swing.JTextField phone;
    private javax.swing.JButton save;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTextField startingYear;
    private javax.swing.JButton studentBtn;
    private javax.swing.JButton teacherBtn;
    // End of variables declaration//GEN-END:variables
}
